### ISSUE TITLE
add build scripts

### ISSUE THREAD

**Issue by knoguchi** [grafana-druid-plugin/druidplugin#4]
Please add Grunt or Gulp build scripts.    I need the reliable build system so I can contribute to the project.

**Comment by abhisant** [comment]
Sorry for the late response. I am currently traveling out of the country for 1 month on a vacation ( with intermittent internet connectivity). I will try to find some time out of my vacation to add this.

**Comment by hmermerkaya** [comment]
I need  build scripts too, I could make some contributions to the project. 
Based on our needs, I  added the following features to Kenji Noguchi work. 
1. Shifting time forward so that one can compare for an instance the data of the last week with that of this week in the same time period.
2. Implementing predefined post aggregations and their relevant aggregations read from json file sitting in dist folder with the same name as that of druid datasource.
3. Implementing post aggregation in which either of the aggregations could exist in different datasources. Aggregations from different datasource can be invoked by object-property notation. For example in a datasource labeled as "A" and an aggreation named "agg1", it is 'A.agg1'. Sample usage is in the DruidPanel screenshot.
Please see my github repo https://github.com/hmermerkaya/druidplugin

**Comment by abhisant** [comment]
I am back today late afternoon. I will start working on this repo tomorrow
onwards one bullet at a time.

On Mon, Feb 6, 2017 at 12:59 PM Hamit Mermerkaya <notifications@github.com>
wrote:

I need build scripts too, I could make some contributions to the project.


Based on our needs, I added the following features to Kenji Noguchi work.





   1. Shifting time forward so that one can compare for an instance the
   data of the last week with that of this week in the same time period.

   2. Implementing predefined post aggregations and their relevant
   aggregations read from json file sitting in dist folder with the same name
   as that of druid datasource.

   3. Implementing post aggregation in which either of the aggregations
   could exist in different datasources. Aggregations from different
   datasource can be invoked by object-property notation. For example in a
   datasource labeled as "A" and an aggreation named "agg1", it is 'A.agg1'.
   Sample usage is in the DruidPanel screenshot.


   Please see my github repo https://github.com/hmermerkaya/druidplugin






—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/grafana-druid-plugin/druidplugin/issues/4#issuecomment-277811330>,
or mute the thread

**Comment by knoguchi** [comment]
This plugin made its way to the [official plugin repo](https://grafana.net/plugins/abhisant-druid-datasource/installation).  It means this repo is responsible for the backward compatibility since the general users started using it.  It lacks Druid's critical features such as PostAggregator, granularity=all, timezone handling, the filter expressions that support AND OR, etc etc.

It was too much work for me to keep my fork mergeable state to the upstream while maintaining the backward compatibility, adding new features, and working around [Druid's bad design](https://github.com/druid-io/druid/issues/1926) all at the same time.   Also my fork introduced math expression parsers so it can support calculations beyond the built-in single term avg/min/max aggregation.  That's the time I decided to take my repo off the Github.  I've never meant to create a hostile fork.

If we build v2.0  I would contribute back where we don't have to maintain the backward compatibility.  Going forward we better come up with roadmap to support the Druid's features thoroughly, or design it to be extensible to the least.  What do you think?

By the way @hmermerkaya, the SQL query is not working.  You may want to remove it.  Back then I was planning to add the PlyQL nodejs module to the plugin.  It turned out to be difficult to integrate.

**Comment by abhisant** [comment]
Added build scripts.
