### ISSUE TITLE
Decrease minimal granularity

### ISSUE THREAD

**Issue by lfblue** [grafana-druid-plugin/druidplugin#43]
hi! 

in our company we use druid for realtime monitoring with 1s interval. As i understand, current minimal granularity is 1m. How about to change it? I could do it by myself, but my web development skills is ugly :C

**Comment by kvsurii** [comment]
Will take a look at this.

**Comment by pkarmaka** [comment]
We can change the custom granularity to include option for second, but lets keep the default as minute.

**Comment by knoguchi** [comment]
none is rarely useful but if we add it why not other supported granularities as well?  Per Druid documentation, the supported granularity strings are: all, none, second, minute, fifteen_minute, thirty_minute, hour, day, week, month, quarter and year.

**Comment by kvsurii** [comment]
Agree that none is rarely useful. It was just something that I added to address this issue. We could add all other granularities as well. Let me know if you think I should add it. I don't see a use of quarter and year granularity from a grafana usecase though.

**Comment by RestfulBlue** [comment]
i think main problem using none granularity with grafana is empty buckets. 
according to docs : 
http://druid.io/docs/latest/querying/timeseriesquery.html
druid support possibility to skip empty buckets adding flag skipEmptyBuckets to context

{
  "queryType": "timeseries",
  "dataSource": "sample_datasource",
  "granularity": "day",
  "aggregations": [
    { "type": "longSum", "name": "sample_name1", "fieldName": "sample_fieldName1" }
  ],
  "intervals": [ "2012-01-01T00:00:00.000/2012-01-04T00:00:00.000" ],
  "context" : {
    "skipEmptyBuckets": "true"
  }
}
i think adding checkbox to add this flag will make it usable in many place. In some place we collect data with 1s interval. But due to some different lags, sometime 2 metrics can be writed with same second. To avoid visualization problem with second granularity we should add post aggregation. Also with that situation come empty bucket, as 2 metrics have some time, so chart look strange in some place. Using none granularity and skipEmptyBuckets will make chart look as it is, without empty buckets and additional post aggregation.
